#
# Transaction Monitor General Makefile
#
# File:      Makefile
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2013-10-01
# Date:      Last Update 2014-11-13
# Version:   0.5
#

# Load the variables necessary to build the analyser
include ../../shared/config/makefile.config

# Prepare the environment for building the analyser
include ../../shared/config/makefile.analyser

# Load the rules necessary to build the analyser
include ../../shared/config/makefile.rules

# End of file Makefile
