#
# Statistics Collector General Makefile
#
# File:      Makefile
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2017-05-19
# Date:      Last Update 2017-05-19
# Version:   0.1
#

# Load the variables necessary to build the analyser
include ../../shared/config/makefile.config

# Prepare the environment for building the analyser
include ../../shared/config/makefile.analyser

# Load the rules necessary to build the analyser
include ../../shared/config/makefile.rules

# End of file Makefile
