#
# Copyright (C) 2014-2018 Jan Fiedor <fiedorjan@centrum.cz>
#
# This file is part of ANaConDA.
#
# ANaConDA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# ANaConDA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ANaConDA. If not, see <http://www.gnu.org/licenses/>.
#

#
# General rules file for all parts of ANaConDA.
#
# Contains definitions of rules necessary to build the ANaConDA framework, its
#   wrappers and analysers.
#
# File:      makefile.rules
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2014-10-03
# Date:      Last Update 2016-04-05
# Version:   0.6
#

# By default, build the release version of the target
all: release

# Build a debug version of the target
debug: pre-build-debug build-target post-build

# Build a release version of the target
release: pre-build-release build-target post-build

# Prepare the environment for building a debug version of the target
pre-build-debug: pre-build
	$(eval CMAKE_FLAGS := $(CMAKE_FLAGS) -DCMAKE_BUILD_TYPE=Debug -DDEBUG=1)

# Prepare the environment for building a release version of the target
pre-build-release: pre-build
	$(eval CMAKE_FLAGS := $(CMAKE_FLAGS) -DCMAKE_BUILD_TYPE=Release -DRELEASE=1)

# Prepare the environment for building the target
pre-build::
	mkdir -p $(BUILD_DIR)

# Build the target
build-target:
	cd $(BUILD_DIR) && $(CMAKE) $(CMAKE_FLAGS) ../..
	$(MAKE) -C $(BUILD_DIR)

# Execute additional actions after building the target
post-build::

# Install the target
install:
	$(MAKE) -C $(BUILD_DIR) install

# Build the programs needed to test the target
build-tests:
	$(MAKE) -C $(BUILD_DIR) build-tests

# Test the target
test:
	$(MAKE) -C $(BUILD_DIR) test

# Prepare source archive of the target
dist:
	git archive --format=tar.gz --prefix=target-`cat src/target.ver`/ HEAD \
	  > target-`cat src/target.ver`-src.tar.gz

# Cleanup the compiled objects, Makefiles and other stuff created by CMake
clean::
	rm -rf ./build ./include ./lib

# End of file makefile.rules
