#
# Main configuration file for all parts of ANaConDA.
#
# Contains definitions of variables necessary to build the ANaConDA framework,
#   its wrappers and analysers.
#
# File:      makefile.config
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2012-02-21
# Date:      Last Update 2015-08-12
# Version:   0.6
#

# Basic variables
# ---------------

# Are we building a debug version? If yes, set DEBUG=1 before configuring PIN!
ifeq ($(findstring debug, $(MAKECMDGOALS)), debug)
  DEBUG=1
endif

# PIN variables
# -------------

# A root directory where the PIN framework is installed
PIN_ROOT ?= $(PIN_HOME)

# A directory containing PIN configuration files 
ifdef PIN_ROOT
  CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
  CONFIG_ROOT := ../Config
endif

# Include the variables necessary to build with PIN
include $(CONFIG_ROOT)/makefile.config

# ANaConDA variables
# ------------------

# Build the IA32 and Intel64 versions separately
BUILD_DIR = ./build/$(HOST_ARCH)

# Use the GCC 4.x ABI if using the GCC 5.x compiler
ifeq ($(shell uname -s),Linux)
  ifeq ($(shell expr `gcc -dumpversion | cut -f1 -d.` \>= 5),1)
    TOOL_CXXFLAGS+= -fabi-version=2
  endif
endif

# The CMake executable we will use to perform the build 
CMAKE ?= cmake
# We need to pass some information set by the PIN's Makefiles to CMake
CMAKE_PIN_FLAGS  = -DTARGET_LONG="$(HOST_ARCH)"
CMAKE_PIN_FLAGS += -DCXX="$(CXX)"
CMAKE_PIN_FLAGS += -DPIN_CXXFLAGS="$(TOOL_CXXFLAGS)"
CMAKE_PIN_FLAGS += -DPIN_LDFLAGS="$(TOOL_LDFLAGS)"
CMAKE_PIN_FLAGS += -DPIN_LPATHS="$(TOOL_LPATHS)"
CMAKE_PIN_FLAGS += -DPIN_LIBS="$(TOOL_LIBS)"
# General CMake parameters used in all types of build (debug, release, etc.)
CMAKE_FLAGS = -DCMAKE_INSTALL_PREFIX=../.. $(CMAKE_PIN_FLAGS)
# Generate Unix Makefiles when building on Windows using Cygwin
ifeq ($(shell uname -o),Cygwin)
  CMAKE_FLAGS += -G"Unix Makefiles"
endif

# End of file makefile.config
