#
# General rules file for all parts of ANaConDA.
#
# Contains definitions of rules necessary to build the ANaConDA framework, its
#   wrappers and analysers.
#
# File:      makefile.rules
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2014-10-03
# Date:      Last Update 2015-05-31
# Version:   0.4
#

# By default, build the release version of the target
all: release

# Build a debug version of the target
debug: pre-build-debug build-target post-build

# Build a release version of the target
release: pre-build-release build-target post-build

# Prepare the environment for building a debug version of the target
pre-build-debug: pre-build
	$(eval CMAKE_FLAGS := $(CMAKE_FLAGS) -DCMAKE_BUILD_TYPE=Debug -DDEBUG=1)

# Prepare the environment for building a release version of the target
pre-build-release: pre-build
	$(eval CMAKE_FLAGS := $(CMAKE_FLAGS) -DCMAKE_BUILD_TYPE=Release -DRELEASE=1)

# Prepare the environment for building the target
pre-build::
	mkdir -p $(BUILD_DIR)

# Build the target
build-target:
	cd $(BUILD_DIR) && $(CMAKE) $(CMAKE_FLAGS) ../..
	$(MAKE) -C $(BUILD_DIR)

# Execute additional actions after building the target
post-build::

# Install the target
install:
	$(MAKE) -C $(BUILD_DIR) install

# Prepare source archive of the target
dist:
	git archive --format=tar.gz --prefix=target-`cat src/target.ver`/ HEAD \
	  > target-`cat src/target.ver`-src.tar.gz

# Cleanup the compiled objects, Makefiles and other stuff created by CMake
clean::
	rm -rf ./build ./include ./lib

# End of file makefile.rules
