#
# AtomRace Data Race Detector General Makefile
#
# File:      Makefile
# Author:    Jan Fiedor (fiedorjan@centrum.cz)
# Date:      Created 2012-02-22
# Date:      Last Update 2014-10-03
# Version:   0.4
#

# Load the variables necessary to build the analyser
include ../../shared/config/makefile.config

# Load the rules necessary to build the analyser
include ../../shared/config/makefile.rules

# End of file Makefile
